sonar.projectKey=gabrieljloh_project-autotest-01
sonar.organization=gabrieljloh
sonar.projectName=Jest Unit Test
sonar.projectVersion=1.0
sonar.sources=./src
sonar.tests=./test
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=./coverage/lcov.info